from scrapingManager import ScrapingManager
from performAnalysis import PerformAnalysis
import sys

# Author: Jace Ackerman
# Date: 10/24/24
# File: executable.py
# Description: This file is responsible for running the software. This file has a main() 
# that creates all the scrapingManager objects necessary to do obtain all the reviews for all five
# apple watche versions. The main method ensures that this script runs only when called directly.

def main():
    if(len(sys.argv) > 2):
        print("Too many arugments. Type 'scrape' to scrape reviews or 'analyze' to get sentiment analysis")
        return
    
    if(sys.argv[1] == 'scrape'):
        #instatiating objects
        series5 = ScrapingManager("appleWatchSeries5URLS.txt", "series5Reviews.txt")
        series6 = ScrapingManager("appleWatchSeries6URLS.txt", "series6Reviews.txt")
        series7 = ScrapingManager("appleWatchSeries7URLS.txt", "series7Reviews.txt")
        series8 = ScrapingManager("appleWatchSeries8URLS.txt", "series8Reviews.txt")
        series9 = ScrapingManager("appleWatchSeries9URLS.txt", "series9Reviews.txt")
    
        #getting reviews for each product
        series5.getReviewsForProduct()
        series6.getReviewsForProduct()
        series7.getReviewsForProduct()
        series8.getReviewsForProduct()
        series9.getReviewsForProduct()
        
    if(sys.argv[1] == 'analyze'):
        analysis = PerformAnalysis()
        analysis.doAnalysis()
        analysis.fillDataArraysForGraph()
        analysis.sentimentGraph.makePlot("Apple Watch Versions", "Number of Reviews", "Sentiment Analysis of Reviews Generated by Phi3")
        analysis.sentimentGraph.displayPlot()
    
if __name__ == "__main__":
    main()
    
    